### ISSUE TITLE
Error in `dplyr::mutate()`: ! Problem while computing `Weather = purrr::pmap(...)`.

### ISSUE THREAD

**Issue by wilson733** [adriancorrendo/AgrometR#1]
Hi, i have the next error with chrips function. I think chirps package is a new version (Documentation for package ‘chirps’ version 0.1.4)

df.weather.chirps <- weather.chirps(df.input, dpp = 30)
Error in `dplyr::mutate()`:
! Problem while computing `Weather = purrr::pmap(...)`.
Caused by error in `server %in% c("CHC", "ClimateSERV")`:
! argument "server" is missing, with no default
Run `rlang::last_error()` to see where the error occurred.
Called from: signal_abort(cnd, .file)
Browse[1]> 

I try to put server ="CHC", but don´t work.
I read the documentation but i didn´t find the function whather.chirps

**Comment by adriancorrendo** [comment]
Hi, Wilson.

Thanks for reporting this issue.

I just tried and figure it out to fetch the data.

To solve it, please, replace the get_chirps() at L 432 with the following:

```
get_chirps(data.frame(lon = c(lon), lat = c(lat)),
                   c(as.character(sta), as.character(end)),
                   server = "CHC")
```

Otherwise, just download the code again in ~30 min. I will submit the change to the Rmd file.

Cheers.

ADRIAN

**Comment by wilson733** [comment]
Cool, solve it! Thank you!
